/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRunsRouteImport } from './routes/_app/runs'
import { Route as AppRepositoriesRouteImport } from './routes/_app/repositories'
import { Route as AppRepositoriesOwnerRepoRouteImport } from './routes/_app/repositories.$owner.$repo'
import { Route as AppRunsOwnerRepoRunIdRouteImport } from './routes/_app/runs_.$owner.$repo.$runId'
import { Route as AppRepositoriesOwnerRepoRunsRouteImport } from './routes/_app/repositories.$owner.$repo.runs'
import { Route as AppRepositoriesOwnerRepoRunsRunIdRouteImport } from './routes/_app/repositories.$owner.$repo.runs.$runId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesOwnerRepoRoute =
  AppRepositoriesOwnerRepoRouteImport.update({
    id: '/$owner/$repo',
    path: '/$owner/$repo',
    getParentRoute: () => AppRepositoriesRoute,
  } as any)
const AppRunsOwnerRepoRunIdRoute = AppRunsOwnerRepoRunIdRouteImport.update({
  id: '/runs_/$owner/$repo/$runId',
  path: '/runs/$owner/$repo/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesOwnerRepoRunsRoute =
  AppRepositoriesOwnerRepoRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AppRepositoriesOwnerRepoRoute,
  } as any)
const AppRepositoriesOwnerRepoRunsRunIdRoute =
  AppRepositoriesOwnerRepoRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AppRepositoriesOwnerRepoRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/repositories': typeof AppRepositoriesRouteWithChildren
  '/runs': typeof AppRunsRoute
  '/repositories/$owner/$repo': typeof AppRepositoriesOwnerRepoRouteWithChildren
  '/repositories/$owner/$repo/runs': typeof AppRepositoriesOwnerRepoRunsRouteWithChildren
  '/runs/$owner/$repo/$runId': typeof AppRunsOwnerRepoRunIdRoute
  '/repositories/$owner/$repo/runs/$runId': typeof AppRepositoriesOwnerRepoRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/repositories': typeof AppRepositoriesRouteWithChildren
  '/runs': typeof AppRunsRoute
  '/': typeof AppIndexRoute
  '/repositories/$owner/$repo': typeof AppRepositoriesOwnerRepoRouteWithChildren
  '/repositories/$owner/$repo/runs': typeof AppRepositoriesOwnerRepoRunsRouteWithChildren
  '/runs/$owner/$repo/$runId': typeof AppRunsOwnerRepoRunIdRoute
  '/repositories/$owner/$repo/runs/$runId': typeof AppRepositoriesOwnerRepoRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/repositories': typeof AppRepositoriesRouteWithChildren
  '/_app/runs': typeof AppRunsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/repositories/$owner/$repo': typeof AppRepositoriesOwnerRepoRouteWithChildren
  '/_app/repositories/$owner/$repo/runs': typeof AppRepositoriesOwnerRepoRunsRouteWithChildren
  '/_app/runs_/$owner/$repo/$runId': typeof AppRunsOwnerRepoRunIdRoute
  '/_app/repositories/$owner/$repo/runs/$runId': typeof AppRepositoriesOwnerRepoRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/repositories'
    | '/runs'
    | '/repositories/$owner/$repo'
    | '/repositories/$owner/$repo/runs'
    | '/runs/$owner/$repo/$runId'
    | '/repositories/$owner/$repo/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/repositories'
    | '/runs'
    | '/'
    | '/repositories/$owner/$repo'
    | '/repositories/$owner/$repo/runs'
    | '/runs/$owner/$repo/$runId'
    | '/repositories/$owner/$repo/runs/$runId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/repositories'
    | '/_app/runs'
    | '/_app/'
    | '/_app/repositories/$owner/$repo'
    | '/_app/repositories/$owner/$repo/runs'
    | '/_app/runs_/$owner/$repo/$runId'
    | '/_app/repositories/$owner/$repo/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$owner/$repo': {
      id: '/_app/repositories/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/_app/runs_/$owner/$repo/$runId': {
      id: '/_app/runs_/$owner/$repo/$runId'
      path: '/runs/$owner/$repo/$runId'
      fullPath: '/runs/$owner/$repo/$runId'
      preLoaderRoute: typeof AppRunsOwnerRepoRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$owner/$repo/runs': {
      id: '/_app/repositories/$owner/$repo/runs'
      path: '/runs'
      fullPath: '/repositories/$owner/$repo/runs'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoRunsRouteImport
      parentRoute: typeof AppRepositoriesOwnerRepoRoute
    }
    '/_app/repositories/$owner/$repo/runs/$runId': {
      id: '/_app/repositories/$owner/$repo/runs/$runId'
      path: '/$runId'
      fullPath: '/repositories/$owner/$repo/runs/$runId'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoRunsRunIdRouteImport
      parentRoute: typeof AppRepositoriesOwnerRepoRunsRoute
    }
  }
}

interface AppRepositoriesOwnerRepoRunsRouteChildren {
  AppRepositoriesOwnerRepoRunsRunIdRoute: typeof AppRepositoriesOwnerRepoRunsRunIdRoute
}

const AppRepositoriesOwnerRepoRunsRouteChildren: AppRepositoriesOwnerRepoRunsRouteChildren =
  {
    AppRepositoriesOwnerRepoRunsRunIdRoute:
      AppRepositoriesOwnerRepoRunsRunIdRoute,
  }

const AppRepositoriesOwnerRepoRunsRouteWithChildren =
  AppRepositoriesOwnerRepoRunsRoute._addFileChildren(
    AppRepositoriesOwnerRepoRunsRouteChildren,
  )

interface AppRepositoriesOwnerRepoRouteChildren {
  AppRepositoriesOwnerRepoRunsRoute: typeof AppRepositoriesOwnerRepoRunsRouteWithChildren
}

const AppRepositoriesOwnerRepoRouteChildren: AppRepositoriesOwnerRepoRouteChildren =
  {
    AppRepositoriesOwnerRepoRunsRoute:
      AppRepositoriesOwnerRepoRunsRouteWithChildren,
  }

const AppRepositoriesOwnerRepoRouteWithChildren =
  AppRepositoriesOwnerRepoRoute._addFileChildren(
    AppRepositoriesOwnerRepoRouteChildren,
  )

interface AppRepositoriesRouteChildren {
  AppRepositoriesOwnerRepoRoute: typeof AppRepositoriesOwnerRepoRouteWithChildren
}

const AppRepositoriesRouteChildren: AppRepositoriesRouteChildren = {
  AppRepositoriesOwnerRepoRoute: AppRepositoriesOwnerRepoRouteWithChildren,
}

const AppRepositoriesRouteWithChildren = AppRepositoriesRoute._addFileChildren(
  AppRepositoriesRouteChildren,
)

interface AppRouteChildren {
  AppRepositoriesRoute: typeof AppRepositoriesRouteWithChildren
  AppRunsRoute: typeof AppRunsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRunsOwnerRepoRunIdRoute: typeof AppRunsOwnerRepoRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRepositoriesRoute: AppRepositoriesRouteWithChildren,
  AppRunsRoute: AppRunsRoute,
  AppIndexRoute: AppIndexRoute,
  AppRunsOwnerRepoRunIdRoute: AppRunsOwnerRepoRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
